### ISSUE TITLE
is recording the status of a GPIO at 10/5us interval possible?

### ISSUE THREAD

**Issue by federicohyo** [Appyx/gpio-reflect#1]
I would like to record an SBUS signal from a GPIO pin. It is a standard protocol for RC receivers. to be compatible with SBUS, a GPIO read has to be configured as follows:
100'000 Baud rate i.e. one bit every 10 us. 
1 start bit (always hi)
8 Data bits 
1 Even parity bit
2 Stop bits 

do yo think that this module can be applied also for recording and decoding such a signal?

thank you for sharing this good work.
 Federico

**Comment by Appyx** [comment]
The software is capable of microsecond precision using jiffies internally and is based on hardware interrupts, so theoretically you should be ok. 

However, I would recommend a Raspberry Pi with a high clockrate.
